# Generated by Django 5.2.7 on 2025-11-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_rename_users_doctorprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
