# Generated by Django 5.2.7 on 2025-11-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_doctorprofile_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
