# Generated by Django 5.2.7 on 2025-11-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_pharmacy_pharmacyprofile_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='upi_qr',
            field=models.ImageField(blank=True, null=True, upload_to='upi_qr/'),
        ),
    ]
