# Generated by Django 5.2.7 on 2025-11-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='bp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='heartrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='oxygen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
